name: croptype
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - blas=1.0=mkl
  - cudatoolkit=9.2=0
  - cudnn=7.2.1=cuda9.2_0
  - cupti=9.2.148=0
  - intel-openmp=2019.0=118
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2019.0=118
  - numpy=1.15.2=py36h1d66e8a_1
  - numpy-base=1.15.2=py36h81de0dd_1
  - pandas=0.23.4=py36h04863e7_0
  - poppler-data=0.4.9=0
  - pytz=2018.5=py36_0
  - scikit-learn=0.20.0=py36h4989274_1
  - scipy=1.1.0=py36hfa4b5c9_1
  - setuptools=40.4.3=py36_0
  - tensorflow=1.10.0=gpu_py36hcebf108_0
  - tensorflow-base=1.10.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.10.0=hf154084_0
  - wheel=0.32.1=py36_0
  - absl-py=0.5.0=py_0
  - affine=2.2.1=py_0
  - asn1crypto=0.24.0=py36_1003
  - astor=0.7.1=py_0
  - attrs=18.2.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.0.1=py_0
  - boost-cpp=1.67.0=h3a22d5f_0
  - boto3=1.9.20=py_0
  - botocore=1.12.21=py_0
  - bzip2=1.0.6=h470a237_2
  - c-ares=1.14.0=h470a237_0
  - ca-certificates=2018.10.15=ha4d7672_0
  - cairo=1.14.12=he6fea26_5
  - certifi=2018.10.15=py36_1000
  - cffi=1.11.5=py36h5e8e0c9_1
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - click-plugins=1.0.4=py_0
  - cligj=0.5.0=py_0
  - cryptography=2.3.1=py36hdffb7b8_0
  - cryptography-vectors=2.3.1=py36_1000
  - curl=7.61.1=h74213dd_2
  - cycler=0.10.0=py_1
  - dbus=1.13.0=h3a4f0e9_0
  - decorator=4.3.0=py_0
  - docutils=0.14=py36_1001
  - entrypoints=0.2.3=py36_1002
  - expat=2.2.5=hfc679d8_2
  - fontconfig=2.13.1=h65d0f4c_0
  - freetype=2.9.1=h6debe1e_4
  - freexl=1.0.5=h470a237_2
  - gast=0.2.0=py_0
  - geos=3.6.2=hfc679d8_3
  - geotiff=1.4.2=h700e5ad_4
  - gettext=0.19.8.1=h5e8e0c9_1
  - giflib=5.1.4=h470a237_1
  - glib=2.55.0=h464dc38_2
  - gmp=6.1.2=hfc679d8_0
  - grpcio=1.14.1=py36hd60e7a3_0
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.5=h61a6719_0
  - h5py=2.8.0=py36h7eb728f_3
  - hdf4=4.2.13=h951d187_2
  - hdf5=1.10.2=hc401514_2
  - icu=58.2=hfc679d8_0
  - idna=2.7=py36_1002
  - ipykernel=5.1.0=pyh24bf2e0_0
  - ipython=7.0.1=py36h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - jedi=0.13.1=py36_1000
  - jinja2=2.10=py_1
  - jmespath=0.9.3=py_1
  - jpeg=9c=h470a237_1
  - json-c=0.12.1=h470a237_1
  - jsonschema=2.6.0=py36_1002
  - jupyter_client=5.2.3=py_1
  - jupyter_core=4.4.0=py_0
  - kealib=1.4.9=h0bee7d0_2
  - keras=2.2.4=py36_0
  - keras-applications=1.0.4=py_1
  - keras-preprocessing=1.0.2=py_1
  - kiwisolver=1.0.1=py36h2d50403_2
  - krb5=1.16.1=hbb41f41_0
  - libcurl=7.61.1=hbdb9355_2
  - libdap4=3.19.1=h8fe5423_1
  - libedit=3.1.20170329=haf1bffa_1
  - libffi=3.2.1=hfc679d8_5
  - libgdal=2.2.4=hbd6f514_9
  - libgpuarray=0.7.6=h470a237_3
  - libiconv=1.15=h470a237_3
  - libkml=1.3.0=hccc92b1_8
  - libnetcdf=4.6.1=he6cff42_8
  - libpng=1.6.35=ha92aebf_2
  - libpq=10.5=he29860b_0
  - libprotobuf=3.6.1=hd28b015_0
  - libsodium=1.0.16=h470a237_1
  - libspatialite=4.3.0a=hdfcc80b_23
  - libssh2=1.8.0=h5b517e9_2
  - libtiff=4.0.9=he6b73bb_2
  - libuuid=2.32.1=h470a237_2
  - libxcb=1.13=h470a237_2
  - libxml2=2.9.8=h422b904_5
  - mako=1.0.7=py_1
  - markdown=2.6.11=py_0
  - markupsafe=1.0=py36h470a237_1
  - matplotlib-base=3.0.0=py36hc039c98_2
  - mistune=0.8.3=py36h470a237_2
  - mkl_fft=1.0.6=py36_0
  - mkl_random=1.0.1=py36_0
  - nb_conda_kernels=2.1.1=py36_1001
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hfc679d8_1
  - notebook=5.7.0=py36_1000
  - openjpeg=2.3.0=h0e734dc_3
  - openssl=1.0.2p=h470a237_1
  - pandoc=2.3.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pcre=8.41=hfc679d8_3
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pip=18.1=py36_1000
  - pixman=0.34.0=h470a237_3
  - poppler=0.67.0=h4d7e492_3
  - postgresql=10.5=h66035e0_0
  - proj4=4.9.3=h470a237_8
  - prometheus_client=0.4.1=py_0
  - prompt_toolkit=2.0.5=py_0
  - protobuf=3.6.1=py36hfc679d8_1
  - pthread-stubs=0.4=h470a237_1
  - ptyprocess=0.6.0=py36_1000
  - pycparser=2.19=py_0
  - pygments=2.2.0=py_1
  - pygpu=0.7.6=py36h7eb728f_0
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.2.2=py_0
  - pyqt=5.6.0=py36h8210e8a_7
  - pysocks=1.6.8=py36_1002
  - python=3.6.6=h5001a0f_3
  - python-dateutil=2.7.3=py_0
  - pyyaml=3.13=py36h470a237_1
  - pyzmq=17.1.2=py36hae99301_1
  - qt=5.6.2=hf70d934_9
  - rasterio=1.0.8=py36h1b5fcde_0
  - readline=7.0=haf1bffa_1
  - requests=2.20.0=py36_1000
  - s3transfer=0.1.13=py36_1001
  - send2trash=1.5.0=py_0
  - simplegeneric=0.8.1=py_1
  - sip=4.18.1=py36hfc679d8_0
  - six=1.11.0=py36_1001
  - snuggs=1.4.1=py_1
  - sqlite=3.25.2=hb1c47c0_0
  - tensorboard=1.10.0=py36_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py36_1000
  - theano=1.0.3=py36_0
  - tk=8.6.8=ha92aebf_0
  - torchfile=0.1.0=py_0
  - tornado=5.1.1=py36h470a237_0
  - traitlets=4.3.2=py36_1000
  - urllib3=1.23=py36_1001
  - visdom=0.1.8.5=0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - websocket-client=0.54.0=py36_1000
  - werkzeug=0.14.1=py_0
  - xerces-c=3.2.0=h5d6a6da_2
  - xorg-kbproto=1.0.7=h470a237_2
  - xorg-libice=1.0.9=h470a237_4
  - xorg-libsm=1.2.3=h8c8a85c_0
  - xorg-libx11=1.6.6=h470a237_0
  - xorg-libxau=1.0.8=h470a237_6
  - xorg-libxdmcp=1.1.2=h470a237_7
  - xorg-libxext=1.3.3=h470a237_4
  - xorg-libxrender=0.9.10=h470a237_2
  - xorg-renderproto=0.11.1=h470a237_2
  - xorg-xextproto=7.3.0=h470a237_2
  - xorg-xproto=7.0.31=h470a237_7
  - xz=5.2.4=h470a237_1
  - yaml=0.1.7=h470a237_1
  - zeromq=4.2.5=hfc679d8_6
  - zlib=1.2.11=h470a237_3
  - ninja=1.8.2=py36h6bb024c_1
  - olefile=0.46=py36_0
  - pillow=5.3.0=py36h34e0f95_0
  - pytorch=0.4.1=py36_py35_py27__9.0.176_7.1.2_2
  - torchvision=0.2.1=py36_1
  - pip:
    - chainer==5.0.0
    - chainercv==0.11.0
    - cloudpickle==0.6.1
    - dask==0.20.0
    - fcn==6.4.8
    - filelock==3.0.10
    - gdown==3.6.0
    - networkx==2.2
    - python-constraint==1.4.0
    - pywavelets==1.0.1
    - scikit-image==0.14.1
    - tensorboardx==1.4
    - toolz==0.9.0
    - torch==0.4.1.post2
    - torchfcn==1.9.0
    - tqdm==4.28.1
prefix: /home/croptype
